//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataMaster.Models
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class ProfitAdmEntities : DbContext
    {
        public ProfitAdmEntities(string conn) : base(conn)
        {
            Configuration.ProxyCreationEnabled = false;
            ((IObjectContextAdapter)this).ObjectContext.CommandTimeout = 180;
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<par_emp> par_emp { get; set; }
        public virtual DbSet<pvArticuloExt> pvArticuloExt { get; set; }
        public virtual DbSet<pvCaja> pvCaja { get; set; }
        public virtual DbSet<pvCobroExt> pvCobroExt { get; set; }
        public virtual DbSet<pvCobroTPRengExt> pvCobroTPRengExt { get; set; }
        public virtual DbSet<pvConfigPuntoV> pvConfigPuntoV { get; set; }
        public virtual DbSet<pvConfigPuntoVPrecio> pvConfigPuntoVPrecio { get; set; }
        public virtual DbSet<pvDevolucionClienteExt> pvDevolucionClienteExt { get; set; }
        public virtual DbSet<pvEtiquetaBalanza> pvEtiquetaBalanza { get; set; }
        public virtual DbSet<pvFacturaVentaExt> pvFacturaVentaExt { get; set; }
        public virtual DbSet<pvMovimientoBancoExt> pvMovimientoBancoExt { get; set; }
        public virtual DbSet<pvMovimientoCajaDevolucionExt> pvMovimientoCajaDevolucionExt { get; set; }
        public virtual DbSet<pvMovimientoCajaExt> pvMovimientoCajaExt { get; set; }
        public virtual DbSet<pvParEmp> pvParEmp { get; set; }
        public virtual DbSet<pvRenglonTicket> pvRenglonTicket { get; set; }
        public virtual DbSet<pvTarjetaCreditoExt> pvTarjetaCreditoExt { get; set; }
        public virtual DbSet<pvTipoTarjeta> pvTipoTarjeta { get; set; }
        public virtual DbSet<pvTurno> pvTurno { get; set; }
        public virtual DbSet<pvTurnoExe> pvTurnoExe { get; set; }
        public virtual DbSet<pvValeAlimentacion> pvValeAlimentacion { get; set; }
        public virtual DbSet<pvValeAlimentacionReng> pvValeAlimentacionReng { get; set; }
        public virtual DbSet<saAdiCampo> saAdiCampo { get; set; }
        public virtual DbSet<saAdiGrupo> saAdiGrupo { get; set; }
        public virtual DbSet<saAjPrecioCostoAuto> saAjPrecioCostoAuto { get; set; }
        public virtual DbSet<saAjPrecioCostoM> saAjPrecioCostoM { get; set; }
        public virtual DbSet<saAjPrecioCostoReng> saAjPrecioCostoReng { get; set; }
        public virtual DbSet<saAjuste> saAjuste { get; set; }
        public virtual DbSet<saAjusteReng> saAjusteReng { get; set; }
        public virtual DbSet<saAlmacen> saAlmacen { get; set; }
        public virtual DbSet<saAreaImpresion> saAreaImpresion { get; set; }
        public virtual DbSet<saArtCaracteristica> saArtCaracteristica { get; set; }
        public virtual DbSet<saArtCaracteristicaMov> saArtCaracteristicaMov { get; set; }
        public virtual DbSet<saArtCompuesto> saArtCompuesto { get; set; }
        public virtual DbSet<saArtCompuestoGen> saArtCompuestoGen { get; set; }
        public virtual DbSet<saArtCompuestoGenReng> saArtCompuestoGenReng { get; set; }
        public virtual DbSet<saArtCompuestoReng> saArtCompuestoReng { get; set; }
        public virtual DbSet<saArticulo> saArticulo { get; set; }
        public virtual DbSet<saArtIdentificadorReng> saArtIdentificadorReng { get; set; }
        public virtual DbSet<saArtImagen> saArtImagen { get; set; }
        public virtual DbSet<saArtImportacion> saArtImportacion { get; set; }
        public virtual DbSet<saArtMargen> saArtMargen { get; set; }
        public virtual DbSet<saArtPrecio> saArtPrecio { get; set; }
        public virtual DbSet<saArtProveedorReng> saArtProveedorReng { get; set; }
        public virtual DbSet<saArtRelacionadoReng> saArtRelacionadoReng { get; set; }
        public virtual DbSet<saArtUbicacion> saArtUbicacion { get; set; }
        public virtual DbSet<saArtUnidad> saArtUnidad { get; set; }
        public virtual DbSet<saBanco> saBanco { get; set; }
        public virtual DbSet<saBeneficiario> saBeneficiario { get; set; }
        public virtual DbSet<saCaja> saCaja { get; set; }
        public virtual DbSet<saCatArticulo> saCatArticulo { get; set; }
        public virtual DbSet<saCheque> saCheque { get; set; }
        public virtual DbSet<saChequeDevueltoCompra> saChequeDevueltoCompra { get; set; }
        public virtual DbSet<saChequeDevueltoVenta> saChequeDevueltoVenta { get; set; }
        public virtual DbSet<saChequera> saChequera { get; set; }
        public virtual DbSet<saCliente> saCliente { get; set; }
        public virtual DbSet<saClienteExt> saClienteExt { get; set; }
        public virtual DbSet<saCobro> saCobro { get; set; }
        public virtual DbSet<saCobroDocReng> saCobroDocReng { get; set; }
        public virtual DbSet<saCobroRentenReng> saCobroRentenReng { get; set; }
        public virtual DbSet<saCobroRetenIvaReng> saCobroRetenIvaReng { get; set; }
        public virtual DbSet<saCobroTPReng> saCobroTPReng { get; set; }
        public virtual DbSet<saColor> saColor { get; set; }
        public virtual DbSet<saComisionGeneracion> saComisionGeneracion { get; set; }
        public virtual DbSet<saComisionPrecioArticulo> saComisionPrecioArticulo { get; set; }
        public virtual DbSet<saComisionPrecioCategoria> saComisionPrecioCategoria { get; set; }
        public virtual DbSet<saComisionPrecioLinea> saComisionPrecioLinea { get; set; }
        public virtual DbSet<saComisionRentabArticulo> saComisionRentabArticulo { get; set; }
        public virtual DbSet<saComisionRentabCategoria> saComisionRentabCategoria { get; set; }
        public virtual DbSet<saComisionRentabLinea> saComisionRentabLinea { get; set; }
        public virtual DbSet<saComisionResultado> saComisionResultado { get; set; }
        public virtual DbSet<saComisionTipo> saComisionTipo { get; set; }
        public virtual DbSet<saConcBanco> saConcBanco { get; set; }
        public virtual DbSet<saConciliacionAutoReng> saConciliacionAutoReng { get; set; }
        public virtual DbSet<saConciliacionDetalle> saConciliacionDetalle { get; set; }
        public virtual DbSet<saCondicionPago> saCondicionPago { get; set; }
        public virtual DbSet<saConfigAjuste> saConfigAjuste { get; set; }
        public virtual DbSet<saConfigArticulo> saConfigArticulo { get; set; }
        public virtual DbSet<saConfigCliente> saConfigCliente { get; set; }
        public virtual DbSet<saConfigCobro> saConfigCobro { get; set; }
        public virtual DbSet<saConfigCotizacionCliente> saConfigCotizacionCliente { get; set; }
        public virtual DbSet<saConfigCotizacionProveedor> saConfigCotizacionProveedor { get; set; }
        public virtual DbSet<saConfigDevolucionCliente> saConfigDevolucionCliente { get; set; }
        public virtual DbSet<saConfigDevolucionProveedor> saConfigDevolucionProveedor { get; set; }
        public virtual DbSet<saConfigDistCosto> saConfigDistCosto { get; set; }
        public virtual DbSet<saConfigFacturaCompra> saConfigFacturaCompra { get; set; }
        public virtual DbSet<saConfigFacturaVenta> saConfigFacturaVenta { get; set; }
        public virtual DbSet<saConfigMovBanco> saConfigMovBanco { get; set; }
        public virtual DbSet<saConfigMovCaja> saConfigMovCaja { get; set; }
        public virtual DbSet<saConfigNotaDespachoVenta> saConfigNotaDespachoVenta { get; set; }
        public virtual DbSet<saConfigNotaEntregaVenta> saConfigNotaEntregaVenta { get; set; }
        public virtual DbSet<saConfigNotaRecepcionCompra> saConfigNotaRecepcionCompra { get; set; }
        public virtual DbSet<saConfigOrdenCompra> saConfigOrdenCompra { get; set; }
        public virtual DbSet<saConfigOrdenPago> saConfigOrdenPago { get; set; }
        public virtual DbSet<saConfigPago> saConfigPago { get; set; }
        public virtual DbSet<saConfigPedidoVenta> saConfigPedidoVenta { get; set; }
        public virtual DbSet<saConfigPlantillaCompra> saConfigPlantillaCompra { get; set; }
        public virtual DbSet<saConfigPlantillaVenta> saConfigPlantillaVenta { get; set; }
        public virtual DbSet<saConfigProveedor> saConfigProveedor { get; set; }
        public virtual DbSet<saConfigTraslado> saConfigTraslado { get; set; }
        public virtual DbSet<saConISLR> saConISLR { get; set; }
        public virtual DbSet<saConsecutivo> saConsecutivo { get; set; }
        public virtual DbSet<saConsecutivoTipo> saConsecutivoTipo { get; set; }
        public virtual DbSet<saCostoHistoricoEntrada> saCostoHistoricoEntrada { get; set; }
        public virtual DbSet<saCostoHistoricoSalida> saCostoHistoricoSalida { get; set; }
        public virtual DbSet<saCotizacionCliente> saCotizacionCliente { get; set; }
        public virtual DbSet<saCotizacionClienteReng> saCotizacionClienteReng { get; set; }
        public virtual DbSet<saCotizacionProveedor> saCotizacionProveedor { get; set; }
        public virtual DbSet<saCotizacionProveedorReng> saCotizacionProveedorReng { get; set; }
        public virtual DbSet<saCuentaBancaria> saCuentaBancaria { get; set; }
        public virtual DbSet<saCuentaIngEgr> saCuentaIngEgr { get; set; }
        public virtual DbSet<saDatosDeImportacion> saDatosDeImportacion { get; set; }
        public virtual DbSet<saDepositoBanco> saDepositoBanco { get; set; }
        public virtual DbSet<saDepositoBancoReng> saDepositoBancoReng { get; set; }
        public virtual DbSet<saDescArticulo> saDescArticulo { get; set; }
        public virtual DbSet<saDescCategoria> saDescCategoria { get; set; }
        public virtual DbSet<saDescLinea> saDescLinea { get; set; }
        public virtual DbSet<saDescProntoPago> saDescProntoPago { get; set; }
        public virtual DbSet<saDevolucionCliente> saDevolucionCliente { get; set; }
        public virtual DbSet<saDevolucionClienteReng> saDevolucionClienteReng { get; set; }
        public virtual DbSet<saDevolucionProveedor> saDevolucionProveedor { get; set; }
        public virtual DbSet<saDevolucionProveedorReng> saDevolucionProveedorReng { get; set; }
        public virtual DbSet<saDevolucionProveedorRengExt> saDevolucionProveedorRengExt { get; set; }
        public virtual DbSet<saDistribCosto> saDistribCosto { get; set; }
        public virtual DbSet<saDistribCostoDestinoReng> saDistribCostoDestinoReng { get; set; }
        public virtual DbSet<saDistribCostoOrigenReng> saDistribCostoOrigenReng { get; set; }
        public virtual DbSet<saDistribCostoRelaReng> saDistribCostoRelaReng { get; set; }
        public virtual DbSet<saDocumentoCompra> saDocumentoCompra { get; set; }
        public virtual DbSet<saDocumentoCompraInfoIGTF> saDocumentoCompraInfoIGTF { get; set; }
        public virtual DbSet<saDocumentoCompraReng> saDocumentoCompraReng { get; set; }
        public virtual DbSet<saDocumentoElectronico> saDocumentoElectronico { get; set; }
        public virtual DbSet<saDocumentoImagen> saDocumentoImagen { get; set; }
        public virtual DbSet<saDocumentoVenta> saDocumentoVenta { get; set; }
        public virtual DbSet<saDocumentoVentaInfoIGTF> saDocumentoVentaInfoIGTF { get; set; }
        public virtual DbSet<saDocumentoVentaReng> saDocumentoVentaReng { get; set; }
        public virtual DbSet<saFactCompRengCaracteristicasAdic> saFactCompRengCaracteristicasAdic { get; set; }
        public virtual DbSet<saFactCompRengPesoVolumen> saFactCompRengPesoVolumen { get; set; }
        public virtual DbSet<saFacturaCompra> saFacturaCompra { get; set; }
        public virtual DbSet<saFacturaCompraImportacion> saFacturaCompraImportacion { get; set; }
        public virtual DbSet<saFacturaCompraReng> saFacturaCompraReng { get; set; }
        public virtual DbSet<saFacturaCompraRengExt> saFacturaCompraRengExt { get; set; }
        public virtual DbSet<saFacturaVenta> saFacturaVenta { get; set; }
        public virtual DbSet<saFacturaVentaReng> saFacturaVentaReng { get; set; }
        public virtual DbSet<saGiroCompra> saGiroCompra { get; set; }
        public virtual DbSet<saGiroCompraReng> saGiroCompraReng { get; set; }
        public virtual DbSet<saGiroVenta> saGiroVenta { get; set; }
        public virtual DbSet<saGiroVentaReng> saGiroVentaReng { get; set; }
        public virtual DbSet<saHistoricoEstado> saHistoricoEstado { get; set; }
        public virtual DbSet<saImpMun> saImpMun { get; set; }
        public virtual DbSet<saImpuesto> saImpuesto { get; set; }
        public virtual DbSet<saImpuestoCuentaBancaria> saImpuestoCuentaBancaria { get; set; }
        public virtual DbSet<saImpuestoReng> saImpuestoReng { get; set; }
        public virtual DbSet<saImpuestoSobreVenta> saImpuestoSobreVenta { get; set; }
        public virtual DbSet<saImpuestoSobreVentaReng> saImpuestoSobreVentaReng { get; set; }
        public virtual DbSet<saIncoterm> saIncoterm { get; set; }
        public virtual DbSet<saIntegr> saIntegr { get; set; }
        public virtual DbSet<saInventarioFisico> saInventarioFisico { get; set; }
        public virtual DbSet<saLineaArticulo> saLineaArticulo { get; set; }
        public virtual DbSet<saLoteEntrada> saLoteEntrada { get; set; }
        public virtual DbSet<saLoteSalida> saLoteSalida { get; set; }
        public virtual DbSet<saMoneda> saMoneda { get; set; }
        public virtual DbSet<saMovimientoBanco> saMovimientoBanco { get; set; }
        public virtual DbSet<saMovimientoCaja> saMovimientoCaja { get; set; }
        public virtual DbSet<saNCFInfoDocCompra> saNCFInfoDocCompra { get; set; }
        public virtual DbSet<saNCFInfoDocVenta> saNCFInfoDocVenta { get; set; }
        public virtual DbSet<saNotaDespachoVenta> saNotaDespachoVenta { get; set; }
        public virtual DbSet<saNotaDespachoVentaReng> saNotaDespachoVentaReng { get; set; }
        public virtual DbSet<saNotaEntregaVenta> saNotaEntregaVenta { get; set; }
        public virtual DbSet<saNotaEntregaVentaReng> saNotaEntregaVentaReng { get; set; }
        public virtual DbSet<saNotaRecepcionCompra> saNotaRecepcionCompra { get; set; }
        public virtual DbSet<saNotaRecepcionCompraReng> saNotaRecepcionCompraReng { get; set; }
        public virtual DbSet<saOrdenCompra> saOrdenCompra { get; set; }
        public virtual DbSet<saOrdenCompraReng> saOrdenCompraReng { get; set; }
        public virtual DbSet<saOrdenPago> saOrdenPago { get; set; }
        public virtual DbSet<saOrdenPagoReng> saOrdenPagoReng { get; set; }
        public virtual DbSet<saPago> saPago { get; set; }
        public virtual DbSet<saPagoDocReng> saPagoDocReng { get; set; }
        public virtual DbSet<saPagoRentenReng> saPagoRentenReng { get; set; }
        public virtual DbSet<saPagoRetenIvaReng> saPagoRetenIvaReng { get; set; }
        public virtual DbSet<saPagoTPReng> saPagoTPReng { get; set; }
        public virtual DbSet<saPais> saPais { get; set; }
        public virtual DbSet<saParametroConc> saParametroConc { get; set; }
        public virtual DbSet<saPedidoVenta> saPedidoVenta { get; set; }
        public virtual DbSet<saPedidoVentaReng> saPedidoVentaReng { get; set; }
        public virtual DbSet<saPista> saPista { get; set; }
        public virtual DbSet<saPlanillaFiscal> saPlanillaFiscal { get; set; }
        public virtual DbSet<saPlantillaCompra> saPlantillaCompra { get; set; }
        public virtual DbSet<saPlantillaCompraReng> saPlantillaCompraReng { get; set; }
        public virtual DbSet<saPlantillaCompraReq> saPlantillaCompraReq { get; set; }
        public virtual DbSet<saPlantillaCompraReqRelacion> saPlantillaCompraReqRelacion { get; set; }
        public virtual DbSet<saPlantillaCompraReqRenglon> saPlantillaCompraReqRenglon { get; set; }
        public virtual DbSet<saPlantillaVenta> saPlantillaVenta { get; set; }
        public virtual DbSet<saPlantillaVentaReng> saPlantillaVentaReng { get; set; }
        public virtual DbSet<saProcedencia> saProcedencia { get; set; }
        public virtual DbSet<saProveedor> saProveedor { get; set; }
        public virtual DbSet<saProveedorExt> saProveedorExt { get; set; }
        public virtual DbSet<saPuntoEmision> saPuntoEmision { get; set; }
        public virtual DbSet<saReglaInt> saReglaInt { get; set; }
        public virtual DbSet<saResInventario> saResInventario { get; set; }
        public virtual DbSet<saResInventarioReng> saResInventarioReng { get; set; }
        public virtual DbSet<saSaldoBanco> saSaldoBanco { get; set; }
        public virtual DbSet<saSaldoCaja> saSaldoCaja { get; set; }
        public virtual DbSet<saSegmento> saSegmento { get; set; }
        public virtual DbSet<saSeriales> saSeriales { get; set; }
        public virtual DbSet<saSerie> saSerie { get; set; }
        public virtual DbSet<saSerieTipo> saSerieTipo { get; set; }
        public virtual DbSet<saSerieTipoExt> saSerieTipoExt { get; set; }
        public virtual DbSet<saStockAlmacen> saStockAlmacen { get; set; }
        public virtual DbSet<saSubLinea> saSubLinea { get; set; }
        public virtual DbSet<saSucursal> saSucursal { get; set; }
        public virtual DbSet<saTabuladorIslr> saTabuladorIslr { get; set; }
        public virtual DbSet<saTabuladorIslrReng> saTabuladorIslrReng { get; set; }
        public virtual DbSet<saTarjetaCredito> saTarjetaCredito { get; set; }
        public virtual DbSet<saTasa> saTasa { get; set; }
        public virtual DbSet<saTax> saTax { get; set; }
        public virtual DbSet<saTipoAjuste> saTipoAjuste { get; set; }
        public virtual DbSet<saTipoAnulacionVenta> saTipoAnulacionVenta { get; set; }
        public virtual DbSet<saTipoCliente> saTipoCliente { get; set; }
        public virtual DbSet<saTipoComprobante> saTipoComprobante { get; set; }
        public virtual DbSet<saTipoDocumento> saTipoDocumento { get; set; }
        public virtual DbSet<saTipoGasto> saTipoGasto { get; set; }
        public virtual DbSet<saTipoImagen> saTipoImagen { get; set; }
        public virtual DbSet<saTipoPrecio> saTipoPrecio { get; set; }
        public virtual DbSet<saTipoProveedor> saTipoProveedor { get; set; }
        public virtual DbSet<saTransferenciaEntreCuentas> saTransferenciaEntreCuentas { get; set; }
        public virtual DbSet<saTransporte> saTransporte { get; set; }
        public virtual DbSet<saTraslado> saTraslado { get; set; }
        public virtual DbSet<saTrasladoReng> saTrasladoReng { get; set; }
        public virtual DbSet<saUbicacion> saUbicacion { get; set; }
        public virtual DbSet<saUnidad> saUnidad { get; set; }
        public virtual DbSet<saUnidadTributaria> saUnidadTributaria { get; set; }
        public virtual DbSet<saVendedor> saVendedor { get; set; }
        public virtual DbSet<saZona> saZona { get; set; }
        public virtual DbSet<scCentro> scCentro { get; set; }
        public virtual DbSet<scCuenta> scCuenta { get; set; }
        public virtual DbSet<scGastos> scGastos { get; set; }
        public virtual DbSet<stgFactLoteGen> stgFactLoteGen { get; set; }
        public virtual DbSet<stgFacturaVentaExt> stgFacturaVentaExt { get; set; }
        public virtual DbSet<pvDenominacionesMoneda> pvDenominacionesMoneda { get; set; }
        public virtual DbSet<saArtCrearAut> saArtCrearAut { get; set; }
    
        public virtual ObjectResult<pConsultarStockxAlmacen_Result> pConsultarStockxAlmacen(string pco_art, string pco_alma)
        {
            var pco_artParameter = pco_art != null ?
                new ObjectParameter("pco_art", pco_art) :
                new ObjectParameter("pco_art", typeof(string));
    
            var pco_almaParameter = pco_alma != null ?
                new ObjectParameter("pco_alma", pco_alma) :
                new ObjectParameter("pco_alma", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pConsultarStockxAlmacen_Result>("pConsultarStockxAlmacen", pco_artParameter, pco_almaParameter);
        }
    
        public virtual ObjectResult<pInsertarPedidoVenta_Result> pInsertarPedidoVenta(string sDoc_Num, string sDescrip, string sCo_Cli, string sCo_Tran, string sCo_Mone, string sCo_Cta_Ingr_Egr, string sCo_Ven, string sCo_Cond, Nullable<System.DateTime> sdFec_Emis, Nullable<System.DateTime> sdFec_Venc, Nullable<System.DateTime> sdFec_Reg, Nullable<bool> bAnulado, string sStatus, Nullable<decimal> deTasa, string sN_Control, string sNro_Doc, string sPorc_Desc_Glob, Nullable<decimal> deMonto_Desc_Glob, string sPorc_Reca, Nullable<decimal> deMonto_Reca, Nullable<decimal> deSaldo, Nullable<decimal> deTotal_Bruto, Nullable<decimal> deMonto_Imp, Nullable<decimal> deMonto_Imp2, Nullable<decimal> deMonto_Imp3, Nullable<decimal> deOtros1, Nullable<decimal> deOtros2, Nullable<decimal> deOtros3, Nullable<decimal> deTotal_Neto, string sDis_Cen, string sComentario, string sDir_Ent, Nullable<bool> bContrib, Nullable<bool> bImpresa, string sSalestax, string sImpfis, string sImpfisfac, Nullable<bool> bVen_Ter, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_Us_In, string sCo_Sucu_In, string sRevisado, string sTrasnfe, string sMaquina)
        {
            var sDoc_NumParameter = sDoc_Num != null ?
                new ObjectParameter("sDoc_Num", sDoc_Num) :
                new ObjectParameter("sDoc_Num", typeof(string));
    
            var sDescripParameter = sDescrip != null ?
                new ObjectParameter("sDescrip", sDescrip) :
                new ObjectParameter("sDescrip", typeof(string));
    
            var sCo_CliParameter = sCo_Cli != null ?
                new ObjectParameter("sCo_Cli", sCo_Cli) :
                new ObjectParameter("sCo_Cli", typeof(string));
    
            var sCo_TranParameter = sCo_Tran != null ?
                new ObjectParameter("sCo_Tran", sCo_Tran) :
                new ObjectParameter("sCo_Tran", typeof(string));
    
            var sCo_MoneParameter = sCo_Mone != null ?
                new ObjectParameter("sCo_Mone", sCo_Mone) :
                new ObjectParameter("sCo_Mone", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sCo_VenParameter = sCo_Ven != null ?
                new ObjectParameter("sCo_Ven", sCo_Ven) :
                new ObjectParameter("sCo_Ven", typeof(string));
    
            var sCo_CondParameter = sCo_Cond != null ?
                new ObjectParameter("sCo_Cond", sCo_Cond) :
                new ObjectParameter("sCo_Cond", typeof(string));
    
            var sdFec_EmisParameter = sdFec_Emis.HasValue ?
                new ObjectParameter("sdFec_Emis", sdFec_Emis) :
                new ObjectParameter("sdFec_Emis", typeof(System.DateTime));
    
            var sdFec_VencParameter = sdFec_Venc.HasValue ?
                new ObjectParameter("sdFec_Venc", sdFec_Venc) :
                new ObjectParameter("sdFec_Venc", typeof(System.DateTime));
    
            var sdFec_RegParameter = sdFec_Reg.HasValue ?
                new ObjectParameter("sdFec_Reg", sdFec_Reg) :
                new ObjectParameter("sdFec_Reg", typeof(System.DateTime));
    
            var bAnuladoParameter = bAnulado.HasValue ?
                new ObjectParameter("bAnulado", bAnulado) :
                new ObjectParameter("bAnulado", typeof(bool));
    
            var sStatusParameter = sStatus != null ?
                new ObjectParameter("sStatus", sStatus) :
                new ObjectParameter("sStatus", typeof(string));
    
            var deTasaParameter = deTasa.HasValue ?
                new ObjectParameter("deTasa", deTasa) :
                new ObjectParameter("deTasa", typeof(decimal));
    
            var sN_ControlParameter = sN_Control != null ?
                new ObjectParameter("sN_Control", sN_Control) :
                new ObjectParameter("sN_Control", typeof(string));
    
            var sNro_DocParameter = sNro_Doc != null ?
                new ObjectParameter("sNro_Doc", sNro_Doc) :
                new ObjectParameter("sNro_Doc", typeof(string));
    
            var sPorc_Desc_GlobParameter = sPorc_Desc_Glob != null ?
                new ObjectParameter("sPorc_Desc_Glob", sPorc_Desc_Glob) :
                new ObjectParameter("sPorc_Desc_Glob", typeof(string));
    
            var deMonto_Desc_GlobParameter = deMonto_Desc_Glob.HasValue ?
                new ObjectParameter("deMonto_Desc_Glob", deMonto_Desc_Glob) :
                new ObjectParameter("deMonto_Desc_Glob", typeof(decimal));
    
            var sPorc_RecaParameter = sPorc_Reca != null ?
                new ObjectParameter("sPorc_Reca", sPorc_Reca) :
                new ObjectParameter("sPorc_Reca", typeof(string));
    
            var deMonto_RecaParameter = deMonto_Reca.HasValue ?
                new ObjectParameter("deMonto_Reca", deMonto_Reca) :
                new ObjectParameter("deMonto_Reca", typeof(decimal));
    
            var deSaldoParameter = deSaldo.HasValue ?
                new ObjectParameter("deSaldo", deSaldo) :
                new ObjectParameter("deSaldo", typeof(decimal));
    
            var deTotal_BrutoParameter = deTotal_Bruto.HasValue ?
                new ObjectParameter("deTotal_Bruto", deTotal_Bruto) :
                new ObjectParameter("deTotal_Bruto", typeof(decimal));
    
            var deMonto_ImpParameter = deMonto_Imp.HasValue ?
                new ObjectParameter("deMonto_Imp", deMonto_Imp) :
                new ObjectParameter("deMonto_Imp", typeof(decimal));
    
            var deMonto_Imp2Parameter = deMonto_Imp2.HasValue ?
                new ObjectParameter("deMonto_Imp2", deMonto_Imp2) :
                new ObjectParameter("deMonto_Imp2", typeof(decimal));
    
            var deMonto_Imp3Parameter = deMonto_Imp3.HasValue ?
                new ObjectParameter("deMonto_Imp3", deMonto_Imp3) :
                new ObjectParameter("deMonto_Imp3", typeof(decimal));
    
            var deOtros1Parameter = deOtros1.HasValue ?
                new ObjectParameter("deOtros1", deOtros1) :
                new ObjectParameter("deOtros1", typeof(decimal));
    
            var deOtros2Parameter = deOtros2.HasValue ?
                new ObjectParameter("deOtros2", deOtros2) :
                new ObjectParameter("deOtros2", typeof(decimal));
    
            var deOtros3Parameter = deOtros3.HasValue ?
                new ObjectParameter("deOtros3", deOtros3) :
                new ObjectParameter("deOtros3", typeof(decimal));
    
            var deTotal_NetoParameter = deTotal_Neto.HasValue ?
                new ObjectParameter("deTotal_Neto", deTotal_Neto) :
                new ObjectParameter("deTotal_Neto", typeof(decimal));
    
            var sDis_CenParameter = sDis_Cen != null ?
                new ObjectParameter("sDis_Cen", sDis_Cen) :
                new ObjectParameter("sDis_Cen", typeof(string));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var sDir_EntParameter = sDir_Ent != null ?
                new ObjectParameter("sDir_Ent", sDir_Ent) :
                new ObjectParameter("sDir_Ent", typeof(string));
    
            var bContribParameter = bContrib.HasValue ?
                new ObjectParameter("bContrib", bContrib) :
                new ObjectParameter("bContrib", typeof(bool));
    
            var bImpresaParameter = bImpresa.HasValue ?
                new ObjectParameter("bImpresa", bImpresa) :
                new ObjectParameter("bImpresa", typeof(bool));
    
            var sSalestaxParameter = sSalestax != null ?
                new ObjectParameter("sSalestax", sSalestax) :
                new ObjectParameter("sSalestax", typeof(string));
    
            var sImpfisParameter = sImpfis != null ?
                new ObjectParameter("sImpfis", sImpfis) :
                new ObjectParameter("sImpfis", typeof(string));
    
            var sImpfisfacParameter = sImpfisfac != null ?
                new ObjectParameter("sImpfisfac", sImpfisfac) :
                new ObjectParameter("sImpfisfac", typeof(string));
    
            var bVen_TerParameter = bVen_Ter.HasValue ?
                new ObjectParameter("bVen_Ter", bVen_Ter) :
                new ObjectParameter("bVen_Ter", typeof(bool));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_Us_InParameter = sCo_Us_In != null ?
                new ObjectParameter("sCo_Us_In", sCo_Us_In) :
                new ObjectParameter("sCo_Us_In", typeof(string));
    
            var sCo_Sucu_InParameter = sCo_Sucu_In != null ?
                new ObjectParameter("sCo_Sucu_In", sCo_Sucu_In) :
                new ObjectParameter("sCo_Sucu_In", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pInsertarPedidoVenta_Result>("pInsertarPedidoVenta", sDoc_NumParameter, sDescripParameter, sCo_CliParameter, sCo_TranParameter, sCo_MoneParameter, sCo_Cta_Ingr_EgrParameter, sCo_VenParameter, sCo_CondParameter, sdFec_EmisParameter, sdFec_VencParameter, sdFec_RegParameter, bAnuladoParameter, sStatusParameter, deTasaParameter, sN_ControlParameter, sNro_DocParameter, sPorc_Desc_GlobParameter, deMonto_Desc_GlobParameter, sPorc_RecaParameter, deMonto_RecaParameter, deSaldoParameter, deTotal_BrutoParameter, deMonto_ImpParameter, deMonto_Imp2Parameter, deMonto_Imp3Parameter, deOtros1Parameter, deOtros2Parameter, deOtros3Parameter, deTotal_NetoParameter, sDis_CenParameter, sComentarioParameter, sDir_EntParameter, bContribParameter, bImpresaParameter, sSalestaxParameter, sImpfisParameter, sImpfisfacParameter, bVen_TerParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_Us_InParameter, sCo_Sucu_InParameter, sRevisadoParameter, sTrasnfeParameter, sMaquinaParameter);
        }
    
        public virtual ObjectResult<pInsertarRenglonesPedidoVenta_Result> pInsertarRenglonesPedidoVenta(Nullable<int> iReng_Num, string sDoc_Num, string sCo_Art, string sDes_Art, string sCo_Uni, string sSco_Uni, string sCo_Alma, string sCo_Precio, string sTipo_Imp, string sTipo_Imp2, string sTipo_Imp3, Nullable<decimal> deTotal_Art, Nullable<decimal> deSTotal_Art, Nullable<decimal> dePrec_Vta, string sPorc_Desc, Nullable<decimal> deMonto_Desc, Nullable<decimal> deReng_Neto, Nullable<decimal> dePendiente, Nullable<decimal> dePendiente2, Nullable<decimal> deMonto_Desc_Glob, Nullable<decimal> deMonto_reca_Glob, Nullable<decimal> deOtros1_glob, Nullable<decimal> deOtros2_glob, Nullable<decimal> deOtros3_glob, Nullable<decimal> deMonto_imp_afec_glob, Nullable<decimal> deMonto_imp2_afec_glob, Nullable<decimal> deMonto_imp3_afec_glob, string sTipo_Doc, Nullable<System.Guid> gRowguid_Doc, string sNum_Doc, Nullable<decimal> dePorc_Imp, Nullable<decimal> dePorc_Imp2, Nullable<decimal> dePorc_Imp3, Nullable<decimal> deMonto_Imp, Nullable<decimal> deMonto_Imp2, Nullable<decimal> deMonto_Imp3, Nullable<decimal> deOtros, Nullable<decimal> deTotal_Dev, Nullable<decimal> deMonto_Dev, string sComentario, string sDis_Cen, string sCo_Sucu_In, string sCo_Us_In, string sREVISADO, string sTRASNFE, string sMaquina)
        {
            var iReng_NumParameter = iReng_Num.HasValue ?
                new ObjectParameter("iReng_Num", iReng_Num) :
                new ObjectParameter("iReng_Num", typeof(int));
    
            var sDoc_NumParameter = sDoc_Num != null ?
                new ObjectParameter("sDoc_Num", sDoc_Num) :
                new ObjectParameter("sDoc_Num", typeof(string));
    
            var sCo_ArtParameter = sCo_Art != null ?
                new ObjectParameter("sCo_Art", sCo_Art) :
                new ObjectParameter("sCo_Art", typeof(string));
    
            var sDes_ArtParameter = sDes_Art != null ?
                new ObjectParameter("sDes_Art", sDes_Art) :
                new ObjectParameter("sDes_Art", typeof(string));
    
            var sCo_UniParameter = sCo_Uni != null ?
                new ObjectParameter("sCo_Uni", sCo_Uni) :
                new ObjectParameter("sCo_Uni", typeof(string));
    
            var sSco_UniParameter = sSco_Uni != null ?
                new ObjectParameter("sSco_Uni", sSco_Uni) :
                new ObjectParameter("sSco_Uni", typeof(string));
    
            var sCo_AlmaParameter = sCo_Alma != null ?
                new ObjectParameter("sCo_Alma", sCo_Alma) :
                new ObjectParameter("sCo_Alma", typeof(string));
    
            var sCo_PrecioParameter = sCo_Precio != null ?
                new ObjectParameter("sCo_Precio", sCo_Precio) :
                new ObjectParameter("sCo_Precio", typeof(string));
    
            var sTipo_ImpParameter = sTipo_Imp != null ?
                new ObjectParameter("sTipo_Imp", sTipo_Imp) :
                new ObjectParameter("sTipo_Imp", typeof(string));
    
            var sTipo_Imp2Parameter = sTipo_Imp2 != null ?
                new ObjectParameter("sTipo_Imp2", sTipo_Imp2) :
                new ObjectParameter("sTipo_Imp2", typeof(string));
    
            var sTipo_Imp3Parameter = sTipo_Imp3 != null ?
                new ObjectParameter("sTipo_Imp3", sTipo_Imp3) :
                new ObjectParameter("sTipo_Imp3", typeof(string));
    
            var deTotal_ArtParameter = deTotal_Art.HasValue ?
                new ObjectParameter("deTotal_Art", deTotal_Art) :
                new ObjectParameter("deTotal_Art", typeof(decimal));
    
            var deSTotal_ArtParameter = deSTotal_Art.HasValue ?
                new ObjectParameter("deSTotal_Art", deSTotal_Art) :
                new ObjectParameter("deSTotal_Art", typeof(decimal));
    
            var dePrec_VtaParameter = dePrec_Vta.HasValue ?
                new ObjectParameter("dePrec_Vta", dePrec_Vta) :
                new ObjectParameter("dePrec_Vta", typeof(decimal));
    
            var sPorc_DescParameter = sPorc_Desc != null ?
                new ObjectParameter("sPorc_Desc", sPorc_Desc) :
                new ObjectParameter("sPorc_Desc", typeof(string));
    
            var deMonto_DescParameter = deMonto_Desc.HasValue ?
                new ObjectParameter("deMonto_Desc", deMonto_Desc) :
                new ObjectParameter("deMonto_Desc", typeof(decimal));
    
            var deReng_NetoParameter = deReng_Neto.HasValue ?
                new ObjectParameter("deReng_Neto", deReng_Neto) :
                new ObjectParameter("deReng_Neto", typeof(decimal));
    
            var dePendienteParameter = dePendiente.HasValue ?
                new ObjectParameter("dePendiente", dePendiente) :
                new ObjectParameter("dePendiente", typeof(decimal));
    
            var dePendiente2Parameter = dePendiente2.HasValue ?
                new ObjectParameter("dePendiente2", dePendiente2) :
                new ObjectParameter("dePendiente2", typeof(decimal));
    
            var deMonto_Desc_GlobParameter = deMonto_Desc_Glob.HasValue ?
                new ObjectParameter("deMonto_Desc_Glob", deMonto_Desc_Glob) :
                new ObjectParameter("deMonto_Desc_Glob", typeof(decimal));
    
            var deMonto_reca_GlobParameter = deMonto_reca_Glob.HasValue ?
                new ObjectParameter("deMonto_reca_Glob", deMonto_reca_Glob) :
                new ObjectParameter("deMonto_reca_Glob", typeof(decimal));
    
            var deOtros1_globParameter = deOtros1_glob.HasValue ?
                new ObjectParameter("deOtros1_glob", deOtros1_glob) :
                new ObjectParameter("deOtros1_glob", typeof(decimal));
    
            var deOtros2_globParameter = deOtros2_glob.HasValue ?
                new ObjectParameter("deOtros2_glob", deOtros2_glob) :
                new ObjectParameter("deOtros2_glob", typeof(decimal));
    
            var deOtros3_globParameter = deOtros3_glob.HasValue ?
                new ObjectParameter("deOtros3_glob", deOtros3_glob) :
                new ObjectParameter("deOtros3_glob", typeof(decimal));
    
            var deMonto_imp_afec_globParameter = deMonto_imp_afec_glob.HasValue ?
                new ObjectParameter("deMonto_imp_afec_glob", deMonto_imp_afec_glob) :
                new ObjectParameter("deMonto_imp_afec_glob", typeof(decimal));
    
            var deMonto_imp2_afec_globParameter = deMonto_imp2_afec_glob.HasValue ?
                new ObjectParameter("deMonto_imp2_afec_glob", deMonto_imp2_afec_glob) :
                new ObjectParameter("deMonto_imp2_afec_glob", typeof(decimal));
    
            var deMonto_imp3_afec_globParameter = deMonto_imp3_afec_glob.HasValue ?
                new ObjectParameter("deMonto_imp3_afec_glob", deMonto_imp3_afec_glob) :
                new ObjectParameter("deMonto_imp3_afec_glob", typeof(decimal));
    
            var sTipo_DocParameter = sTipo_Doc != null ?
                new ObjectParameter("sTipo_Doc", sTipo_Doc) :
                new ObjectParameter("sTipo_Doc", typeof(string));
    
            var gRowguid_DocParameter = gRowguid_Doc.HasValue ?
                new ObjectParameter("gRowguid_Doc", gRowguid_Doc) :
                new ObjectParameter("gRowguid_Doc", typeof(System.Guid));
    
            var sNum_DocParameter = sNum_Doc != null ?
                new ObjectParameter("sNum_Doc", sNum_Doc) :
                new ObjectParameter("sNum_Doc", typeof(string));
    
            var dePorc_ImpParameter = dePorc_Imp.HasValue ?
                new ObjectParameter("dePorc_Imp", dePorc_Imp) :
                new ObjectParameter("dePorc_Imp", typeof(decimal));
    
            var dePorc_Imp2Parameter = dePorc_Imp2.HasValue ?
                new ObjectParameter("dePorc_Imp2", dePorc_Imp2) :
                new ObjectParameter("dePorc_Imp2", typeof(decimal));
    
            var dePorc_Imp3Parameter = dePorc_Imp3.HasValue ?
                new ObjectParameter("dePorc_Imp3", dePorc_Imp3) :
                new ObjectParameter("dePorc_Imp3", typeof(decimal));
    
            var deMonto_ImpParameter = deMonto_Imp.HasValue ?
                new ObjectParameter("deMonto_Imp", deMonto_Imp) :
                new ObjectParameter("deMonto_Imp", typeof(decimal));
    
            var deMonto_Imp2Parameter = deMonto_Imp2.HasValue ?
                new ObjectParameter("deMonto_Imp2", deMonto_Imp2) :
                new ObjectParameter("deMonto_Imp2", typeof(decimal));
    
            var deMonto_Imp3Parameter = deMonto_Imp3.HasValue ?
                new ObjectParameter("deMonto_Imp3", deMonto_Imp3) :
                new ObjectParameter("deMonto_Imp3", typeof(decimal));
    
            var deOtrosParameter = deOtros.HasValue ?
                new ObjectParameter("deOtros", deOtros) :
                new ObjectParameter("deOtros", typeof(decimal));
    
            var deTotal_DevParameter = deTotal_Dev.HasValue ?
                new ObjectParameter("deTotal_Dev", deTotal_Dev) :
                new ObjectParameter("deTotal_Dev", typeof(decimal));
    
            var deMonto_DevParameter = deMonto_Dev.HasValue ?
                new ObjectParameter("deMonto_Dev", deMonto_Dev) :
                new ObjectParameter("deMonto_Dev", typeof(decimal));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var sDis_CenParameter = sDis_Cen != null ?
                new ObjectParameter("sDis_Cen", sDis_Cen) :
                new ObjectParameter("sDis_Cen", typeof(string));
    
            var sCo_Sucu_InParameter = sCo_Sucu_In != null ?
                new ObjectParameter("sCo_Sucu_In", sCo_Sucu_In) :
                new ObjectParameter("sCo_Sucu_In", typeof(string));
    
            var sCo_Us_InParameter = sCo_Us_In != null ?
                new ObjectParameter("sCo_Us_In", sCo_Us_In) :
                new ObjectParameter("sCo_Us_In", typeof(string));
    
            var sREVISADOParameter = sREVISADO != null ?
                new ObjectParameter("sREVISADO", sREVISADO) :
                new ObjectParameter("sREVISADO", typeof(string));
    
            var sTRASNFEParameter = sTRASNFE != null ?
                new ObjectParameter("sTRASNFE", sTRASNFE) :
                new ObjectParameter("sTRASNFE", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pInsertarRenglonesPedidoVenta_Result>("pInsertarRenglonesPedidoVenta", iReng_NumParameter, sDoc_NumParameter, sCo_ArtParameter, sDes_ArtParameter, sCo_UniParameter, sSco_UniParameter, sCo_AlmaParameter, sCo_PrecioParameter, sTipo_ImpParameter, sTipo_Imp2Parameter, sTipo_Imp3Parameter, deTotal_ArtParameter, deSTotal_ArtParameter, dePrec_VtaParameter, sPorc_DescParameter, deMonto_DescParameter, deReng_NetoParameter, dePendienteParameter, dePendiente2Parameter, deMonto_Desc_GlobParameter, deMonto_reca_GlobParameter, deOtros1_globParameter, deOtros2_globParameter, deOtros3_globParameter, deMonto_imp_afec_globParameter, deMonto_imp2_afec_globParameter, deMonto_imp3_afec_globParameter, sTipo_DocParameter, gRowguid_DocParameter, sNum_DocParameter, dePorc_ImpParameter, dePorc_Imp2Parameter, dePorc_Imp3Parameter, deMonto_ImpParameter, deMonto_Imp2Parameter, deMonto_Imp3Parameter, deOtrosParameter, deTotal_DevParameter, deMonto_DevParameter, sComentarioParameter, sDis_CenParameter, sCo_Sucu_InParameter, sCo_Us_InParameter, sREVISADOParameter, sTRASNFEParameter, sMaquinaParameter);
        }
    
        public virtual ObjectResult<pConsultarStockArticulo_Result> pConsultarStockArticulo(string co_art, string co_alma, string tipo)
        {
            var co_artParameter = co_art != null ?
                new ObjectParameter("co_art", co_art) :
                new ObjectParameter("co_art", typeof(string));
    
            var co_almaParameter = co_alma != null ?
                new ObjectParameter("co_alma", co_alma) :
                new ObjectParameter("co_alma", typeof(string));
    
            var tipoParameter = tipo != null ?
                new ObjectParameter("tipo", tipo) :
                new ObjectParameter("tipo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pConsultarStockArticulo_Result>("pConsultarStockArticulo", co_artParameter, co_almaParameter, tipoParameter);
        }
    
        public virtual ObjectResult<string> pConsecutivoProximo(string sCo_Sucur, string sCo_Consecutivo)
        {
            var sCo_SucurParameter = sCo_Sucur != null ?
                new ObjectParameter("sCo_Sucur", sCo_Sucur) :
                new ObjectParameter("sCo_Sucur", typeof(string));
    
            var sCo_ConsecutivoParameter = sCo_Consecutivo != null ?
                new ObjectParameter("sCo_Consecutivo", sCo_Consecutivo) :
                new ObjectParameter("sCo_Consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<string>("pConsecutivoProximo", sCo_SucurParameter, sCo_ConsecutivoParameter);
        }
    
        public virtual ObjectResult<pSeleccionarUsoSucursalConsecutivoTipo_Result> pSeleccionarUsoSucursalConsecutivoTipo(string sCo_Consecutivo)
        {
            var sCo_ConsecutivoParameter = sCo_Consecutivo != null ?
                new ObjectParameter("sCo_Consecutivo", sCo_Consecutivo) :
                new ObjectParameter("sCo_Consecutivo", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pSeleccionarUsoSucursalConsecutivoTipo_Result>("pSeleccionarUsoSucursalConsecutivoTipo", sCo_ConsecutivoParameter);
        }
    
        public virtual ObjectResult<Nullable<decimal>> pStockActualizar(string sCo_Alma, string sCo_Art, string sCo_Uni, Nullable<decimal> deCantidad, string sTipoStock, Nullable<bool> bSumarStock, Nullable<bool> bPermiteStockNegativo)
        {
            var sCo_AlmaParameter = sCo_Alma != null ?
                new ObjectParameter("sCo_Alma", sCo_Alma) :
                new ObjectParameter("sCo_Alma", typeof(string));
    
            var sCo_ArtParameter = sCo_Art != null ?
                new ObjectParameter("sCo_Art", sCo_Art) :
                new ObjectParameter("sCo_Art", typeof(string));
    
            var sCo_UniParameter = sCo_Uni != null ?
                new ObjectParameter("sCo_Uni", sCo_Uni) :
                new ObjectParameter("sCo_Uni", typeof(string));
    
            var deCantidadParameter = deCantidad.HasValue ?
                new ObjectParameter("deCantidad", deCantidad) :
                new ObjectParameter("deCantidad", typeof(decimal));
    
            var sTipoStockParameter = sTipoStock != null ?
                new ObjectParameter("sTipoStock", sTipoStock) :
                new ObjectParameter("sTipoStock", typeof(string));
    
            var bSumarStockParameter = bSumarStock.HasValue ?
                new ObjectParameter("bSumarStock", bSumarStock) :
                new ObjectParameter("bSumarStock", typeof(bool));
    
            var bPermiteStockNegativoParameter = bPermiteStockNegativo.HasValue ?
                new ObjectParameter("bPermiteStockNegativo", bPermiteStockNegativo) :
                new ObjectParameter("bPermiteStockNegativo", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<Nullable<decimal>>("pStockActualizar", sCo_AlmaParameter, sCo_ArtParameter, sCo_UniParameter, deCantidadParameter, sTipoStockParameter, bSumarStockParameter, bPermiteStockNegativoParameter);
        }
    
        public virtual ObjectResult<pActualizarPedidoVenta_Result> pActualizarPedidoVenta(string sDoc_Num, string sDoc_NumOri, string sDescrip, string sCo_Cli, string sCo_Tran, string sCo_Mone, string sCo_Cta_Ingr_Egr, string sCo_Ven, string sCo_Cond, Nullable<System.DateTime> sdFec_Emis, Nullable<System.DateTime> sdFec_Venc, Nullable<System.DateTime> sdFec_Reg, Nullable<bool> bAnulado, string sStatus, Nullable<decimal> deTasa, string sN_Control, string sNro_Doc, string sPorc_Desc_Glob, Nullable<decimal> deMonto_Desc_Glob, string sPorc_Reca, Nullable<decimal> deMonto_reca, Nullable<decimal> deSaldo, Nullable<decimal> deTotal_Bruto, Nullable<decimal> deMonto_Imp, Nullable<decimal> deMonto_Imp2, Nullable<decimal> deMonto_Imp3, Nullable<decimal> deOtros1, Nullable<decimal> deOtros2, Nullable<decimal> deOtros3, Nullable<decimal> deTotal_Neto, string sComentario, string sDir_Ent, Nullable<bool> bContrib, Nullable<bool> bImpresa, string sSalestax, string sImpfis, string sImpfisfac, Nullable<bool> bVen_Ter, string sDis_Cen, string sCampo1, string sCampo2, string sCampo3, string sCampo4, string sCampo5, string sCampo6, string sCampo7, string sCampo8, string sCo_Us_Mo, string sCo_Sucu_Mo, string sRevisado, string sTrasnfe, string sMaquina, byte[] tsValidador, string sCampos, Nullable<System.Guid> gRowguid)
        {
            var sDoc_NumParameter = sDoc_Num != null ?
                new ObjectParameter("sDoc_Num", sDoc_Num) :
                new ObjectParameter("sDoc_Num", typeof(string));
    
            var sDoc_NumOriParameter = sDoc_NumOri != null ?
                new ObjectParameter("sDoc_NumOri", sDoc_NumOri) :
                new ObjectParameter("sDoc_NumOri", typeof(string));
    
            var sDescripParameter = sDescrip != null ?
                new ObjectParameter("sDescrip", sDescrip) :
                new ObjectParameter("sDescrip", typeof(string));
    
            var sCo_CliParameter = sCo_Cli != null ?
                new ObjectParameter("sCo_Cli", sCo_Cli) :
                new ObjectParameter("sCo_Cli", typeof(string));
    
            var sCo_TranParameter = sCo_Tran != null ?
                new ObjectParameter("sCo_Tran", sCo_Tran) :
                new ObjectParameter("sCo_Tran", typeof(string));
    
            var sCo_MoneParameter = sCo_Mone != null ?
                new ObjectParameter("sCo_Mone", sCo_Mone) :
                new ObjectParameter("sCo_Mone", typeof(string));
    
            var sCo_Cta_Ingr_EgrParameter = sCo_Cta_Ingr_Egr != null ?
                new ObjectParameter("sCo_Cta_Ingr_Egr", sCo_Cta_Ingr_Egr) :
                new ObjectParameter("sCo_Cta_Ingr_Egr", typeof(string));
    
            var sCo_VenParameter = sCo_Ven != null ?
                new ObjectParameter("sCo_Ven", sCo_Ven) :
                new ObjectParameter("sCo_Ven", typeof(string));
    
            var sCo_CondParameter = sCo_Cond != null ?
                new ObjectParameter("sCo_Cond", sCo_Cond) :
                new ObjectParameter("sCo_Cond", typeof(string));
    
            var sdFec_EmisParameter = sdFec_Emis.HasValue ?
                new ObjectParameter("sdFec_Emis", sdFec_Emis) :
                new ObjectParameter("sdFec_Emis", typeof(System.DateTime));
    
            var sdFec_VencParameter = sdFec_Venc.HasValue ?
                new ObjectParameter("sdFec_Venc", sdFec_Venc) :
                new ObjectParameter("sdFec_Venc", typeof(System.DateTime));
    
            var sdFec_RegParameter = sdFec_Reg.HasValue ?
                new ObjectParameter("sdFec_Reg", sdFec_Reg) :
                new ObjectParameter("sdFec_Reg", typeof(System.DateTime));
    
            var bAnuladoParameter = bAnulado.HasValue ?
                new ObjectParameter("bAnulado", bAnulado) :
                new ObjectParameter("bAnulado", typeof(bool));
    
            var sStatusParameter = sStatus != null ?
                new ObjectParameter("sStatus", sStatus) :
                new ObjectParameter("sStatus", typeof(string));
    
            var deTasaParameter = deTasa.HasValue ?
                new ObjectParameter("deTasa", deTasa) :
                new ObjectParameter("deTasa", typeof(decimal));
    
            var sN_ControlParameter = sN_Control != null ?
                new ObjectParameter("sN_Control", sN_Control) :
                new ObjectParameter("sN_Control", typeof(string));
    
            var sNro_DocParameter = sNro_Doc != null ?
                new ObjectParameter("sNro_Doc", sNro_Doc) :
                new ObjectParameter("sNro_Doc", typeof(string));
    
            var sPorc_Desc_GlobParameter = sPorc_Desc_Glob != null ?
                new ObjectParameter("sPorc_Desc_Glob", sPorc_Desc_Glob) :
                new ObjectParameter("sPorc_Desc_Glob", typeof(string));
    
            var deMonto_Desc_GlobParameter = deMonto_Desc_Glob.HasValue ?
                new ObjectParameter("deMonto_Desc_Glob", deMonto_Desc_Glob) :
                new ObjectParameter("deMonto_Desc_Glob", typeof(decimal));
    
            var sPorc_RecaParameter = sPorc_Reca != null ?
                new ObjectParameter("sPorc_Reca", sPorc_Reca) :
                new ObjectParameter("sPorc_Reca", typeof(string));
    
            var deMonto_recaParameter = deMonto_reca.HasValue ?
                new ObjectParameter("deMonto_reca", deMonto_reca) :
                new ObjectParameter("deMonto_reca", typeof(decimal));
    
            var deSaldoParameter = deSaldo.HasValue ?
                new ObjectParameter("deSaldo", deSaldo) :
                new ObjectParameter("deSaldo", typeof(decimal));
    
            var deTotal_BrutoParameter = deTotal_Bruto.HasValue ?
                new ObjectParameter("deTotal_Bruto", deTotal_Bruto) :
                new ObjectParameter("deTotal_Bruto", typeof(decimal));
    
            var deMonto_ImpParameter = deMonto_Imp.HasValue ?
                new ObjectParameter("deMonto_Imp", deMonto_Imp) :
                new ObjectParameter("deMonto_Imp", typeof(decimal));
    
            var deMonto_Imp2Parameter = deMonto_Imp2.HasValue ?
                new ObjectParameter("deMonto_Imp2", deMonto_Imp2) :
                new ObjectParameter("deMonto_Imp2", typeof(decimal));
    
            var deMonto_Imp3Parameter = deMonto_Imp3.HasValue ?
                new ObjectParameter("deMonto_Imp3", deMonto_Imp3) :
                new ObjectParameter("deMonto_Imp3", typeof(decimal));
    
            var deOtros1Parameter = deOtros1.HasValue ?
                new ObjectParameter("deOtros1", deOtros1) :
                new ObjectParameter("deOtros1", typeof(decimal));
    
            var deOtros2Parameter = deOtros2.HasValue ?
                new ObjectParameter("deOtros2", deOtros2) :
                new ObjectParameter("deOtros2", typeof(decimal));
    
            var deOtros3Parameter = deOtros3.HasValue ?
                new ObjectParameter("deOtros3", deOtros3) :
                new ObjectParameter("deOtros3", typeof(decimal));
    
            var deTotal_NetoParameter = deTotal_Neto.HasValue ?
                new ObjectParameter("deTotal_Neto", deTotal_Neto) :
                new ObjectParameter("deTotal_Neto", typeof(decimal));
    
            var sComentarioParameter = sComentario != null ?
                new ObjectParameter("sComentario", sComentario) :
                new ObjectParameter("sComentario", typeof(string));
    
            var sDir_EntParameter = sDir_Ent != null ?
                new ObjectParameter("sDir_Ent", sDir_Ent) :
                new ObjectParameter("sDir_Ent", typeof(string));
    
            var bContribParameter = bContrib.HasValue ?
                new ObjectParameter("bContrib", bContrib) :
                new ObjectParameter("bContrib", typeof(bool));
    
            var bImpresaParameter = bImpresa.HasValue ?
                new ObjectParameter("bImpresa", bImpresa) :
                new ObjectParameter("bImpresa", typeof(bool));
    
            var sSalestaxParameter = sSalestax != null ?
                new ObjectParameter("sSalestax", sSalestax) :
                new ObjectParameter("sSalestax", typeof(string));
    
            var sImpfisParameter = sImpfis != null ?
                new ObjectParameter("sImpfis", sImpfis) :
                new ObjectParameter("sImpfis", typeof(string));
    
            var sImpfisfacParameter = sImpfisfac != null ?
                new ObjectParameter("sImpfisfac", sImpfisfac) :
                new ObjectParameter("sImpfisfac", typeof(string));
    
            var bVen_TerParameter = bVen_Ter.HasValue ?
                new ObjectParameter("bVen_Ter", bVen_Ter) :
                new ObjectParameter("bVen_Ter", typeof(bool));
    
            var sDis_CenParameter = sDis_Cen != null ?
                new ObjectParameter("sDis_Cen", sDis_Cen) :
                new ObjectParameter("sDis_Cen", typeof(string));
    
            var sCampo1Parameter = sCampo1 != null ?
                new ObjectParameter("sCampo1", sCampo1) :
                new ObjectParameter("sCampo1", typeof(string));
    
            var sCampo2Parameter = sCampo2 != null ?
                new ObjectParameter("sCampo2", sCampo2) :
                new ObjectParameter("sCampo2", typeof(string));
    
            var sCampo3Parameter = sCampo3 != null ?
                new ObjectParameter("sCampo3", sCampo3) :
                new ObjectParameter("sCampo3", typeof(string));
    
            var sCampo4Parameter = sCampo4 != null ?
                new ObjectParameter("sCampo4", sCampo4) :
                new ObjectParameter("sCampo4", typeof(string));
    
            var sCampo5Parameter = sCampo5 != null ?
                new ObjectParameter("sCampo5", sCampo5) :
                new ObjectParameter("sCampo5", typeof(string));
    
            var sCampo6Parameter = sCampo6 != null ?
                new ObjectParameter("sCampo6", sCampo6) :
                new ObjectParameter("sCampo6", typeof(string));
    
            var sCampo7Parameter = sCampo7 != null ?
                new ObjectParameter("sCampo7", sCampo7) :
                new ObjectParameter("sCampo7", typeof(string));
    
            var sCampo8Parameter = sCampo8 != null ?
                new ObjectParameter("sCampo8", sCampo8) :
                new ObjectParameter("sCampo8", typeof(string));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var sRevisadoParameter = sRevisado != null ?
                new ObjectParameter("sRevisado", sRevisado) :
                new ObjectParameter("sRevisado", typeof(string));
    
            var sTrasnfeParameter = sTrasnfe != null ?
                new ObjectParameter("sTrasnfe", sTrasnfe) :
                new ObjectParameter("sTrasnfe", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var sCamposParameter = sCampos != null ?
                new ObjectParameter("sCampos", sCampos) :
                new ObjectParameter("sCampos", typeof(string));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pActualizarPedidoVenta_Result>("pActualizarPedidoVenta", sDoc_NumParameter, sDoc_NumOriParameter, sDescripParameter, sCo_CliParameter, sCo_TranParameter, sCo_MoneParameter, sCo_Cta_Ingr_EgrParameter, sCo_VenParameter, sCo_CondParameter, sdFec_EmisParameter, sdFec_VencParameter, sdFec_RegParameter, bAnuladoParameter, sStatusParameter, deTasaParameter, sN_ControlParameter, sNro_DocParameter, sPorc_Desc_GlobParameter, deMonto_Desc_GlobParameter, sPorc_RecaParameter, deMonto_recaParameter, deSaldoParameter, deTotal_BrutoParameter, deMonto_ImpParameter, deMonto_Imp2Parameter, deMonto_Imp3Parameter, deOtros1Parameter, deOtros2Parameter, deOtros3Parameter, deTotal_NetoParameter, sComentarioParameter, sDir_EntParameter, bContribParameter, bImpresaParameter, sSalestaxParameter, sImpfisParameter, sImpfisfacParameter, bVen_TerParameter, sDis_CenParameter, sCampo1Parameter, sCampo2Parameter, sCampo3Parameter, sCampo4Parameter, sCampo5Parameter, sCampo6Parameter, sCampo7Parameter, sCampo8Parameter, sCo_Us_MoParameter, sCo_Sucu_MoParameter, sRevisadoParameter, sTrasnfeParameter, sMaquinaParameter, tsValidadorParameter, sCamposParameter, gRowguidParameter);
        }
    
        public virtual int pEliminarPedidoVenta(string sDoc_NumOri, byte[] tsValidador, string sMaquina, string sCo_Us_Mo, string sCo_Sucu_Mo, Nullable<System.Guid> gRowguid)
        {
            var sDoc_NumOriParameter = sDoc_NumOri != null ?
                new ObjectParameter("sDoc_NumOri", sDoc_NumOri) :
                new ObjectParameter("sDoc_NumOri", typeof(string));
    
            var tsValidadorParameter = tsValidador != null ?
                new ObjectParameter("tsValidador", tsValidador) :
                new ObjectParameter("tsValidador", typeof(byte[]));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pEliminarPedidoVenta", sDoc_NumOriParameter, tsValidadorParameter, sMaquinaParameter, sCo_Us_MoParameter, sCo_Sucu_MoParameter, gRowguidParameter);
        }
    
        public virtual int pEliminarRenglonesPedidoVenta(string sDoc_NumOri, Nullable<int> iReng_NumOri, string sCo_Us_Mo, string sMaquina, string sCo_Sucu_Mo, Nullable<System.Guid> gRowguid)
        {
            var sDoc_NumOriParameter = sDoc_NumOri != null ?
                new ObjectParameter("sDoc_NumOri", sDoc_NumOri) :
                new ObjectParameter("sDoc_NumOri", typeof(string));
    
            var iReng_NumOriParameter = iReng_NumOri.HasValue ?
                new ObjectParameter("iReng_NumOri", iReng_NumOri) :
                new ObjectParameter("iReng_NumOri", typeof(int));
    
            var sCo_Us_MoParameter = sCo_Us_Mo != null ?
                new ObjectParameter("sCo_Us_Mo", sCo_Us_Mo) :
                new ObjectParameter("sCo_Us_Mo", typeof(string));
    
            var sMaquinaParameter = sMaquina != null ?
                new ObjectParameter("sMaquina", sMaquina) :
                new ObjectParameter("sMaquina", typeof(string));
    
            var sCo_Sucu_MoParameter = sCo_Sucu_Mo != null ?
                new ObjectParameter("sCo_Sucu_Mo", sCo_Sucu_Mo) :
                new ObjectParameter("sCo_Sucu_Mo", typeof(string));
    
            var gRowguidParameter = gRowguid.HasValue ?
                new ObjectParameter("gRowguid", gRowguid) :
                new ObjectParameter("gRowguid", typeof(System.Guid));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pEliminarRenglonesPedidoVenta", sDoc_NumOriParameter, iReng_NumOriParameter, sCo_Us_MoParameter, sMaquinaParameter, sCo_Sucu_MoParameter, gRowguidParameter);
        }
    
        public virtual ObjectResult<pObtenerFechaImpuestoSobreVenta_Result> pObtenerFechaImpuestoSobreVenta(Nullable<System.DateTime> dtFecha, Nullable<bool> bVentas)
        {
            var dtFechaParameter = dtFecha.HasValue ?
                new ObjectParameter("dtFecha", dtFecha) :
                new ObjectParameter("dtFecha", typeof(System.DateTime));
    
            var bVentasParameter = bVentas.HasValue ?
                new ObjectParameter("bVentas", bVentas) :
                new ObjectParameter("bVentas", typeof(bool));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction<pObtenerFechaImpuestoSobreVenta_Result>("pObtenerFechaImpuestoSobreVenta", dtFechaParameter, bVentasParameter);
        }
    
        public virtual int pStockPendienteActualizar(Nullable<System.Guid> uniRowGuidOri, Nullable<decimal> deCantidad, string sTipoDocumento)
        {
            var uniRowGuidOriParameter = uniRowGuidOri.HasValue ?
                new ObjectParameter("uniRowGuidOri", uniRowGuidOri) :
                new ObjectParameter("uniRowGuidOri", typeof(System.Guid));
    
            var deCantidadParameter = deCantidad.HasValue ?
                new ObjectParameter("deCantidad", deCantidad) :
                new ObjectParameter("deCantidad", typeof(decimal));
    
            var sTipoDocumentoParameter = sTipoDocumento != null ?
                new ObjectParameter("sTipoDocumento", sTipoDocumento) :
                new ObjectParameter("sTipoDocumento", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("pStockPendienteActualizar", uniRowGuidOriParameter, deCantidadParameter, sTipoDocumentoParameter);
        }
    }
}
